kind: pipeline
type: docker
name: HowMuchDoesThisMeetingcost

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm test
-name: build
  image: node
  commands:
  -npm install
  -npm run build